Here's some pearls for you
MUNComputerScienceSociety/ChallengeSet-W2020 pull request #16
Opened 2020-01-25 00:52 UTC by SteveParson

2020-01-25 00:52 UTC, SteveParson commented
@nint8835 @jackharrhy @theteamaker @koalasthegreat

2020-01-25 20:47 UTC, nint8835 approved these changes

2020-01-27 16:51 UTC, jackharrhy requested changes
4thought.pl :heavy_check_mark: 
~~icanguessthedatastructure.pl :x: , output didn't match answer~~ removed :)
messybanner.pl :heavy_check_mark: 
numberfun.c :heavy_check_mark: 
numberfun.pl :heavy_check_mark: 
quickestimate.c :heavy_check_mark: 
quickestimate.pl :heavy_check_mark: 
sevenwonders.c :heavy_check_mark: 
sevenwonders.pl :heavy_check_mark:

2020-02-09 02:10 UTC, jackharrhy approved these changes

2020-02-09 02:10 UTC, merged