my problems!
MUNComputerScienceSociety/ChallengeSet-W2020 pull request #17
Opened 2020-01-25 01:18 UTC by theteamaker

2020-01-25 20:59 UTC, nint8835 submitted a review, later dismissed

2020-01-25 20:59 UTC, nint8835 commented on week-01/theteamaker/aboveaverage/1.in
> +5
Test files should not be included

2020-01-27 15:42 UTC, theteamaker commented on week-01/theteamaker/aboveaverage/1.in
> +5
fixed

2020-01-27 17:06 UTC, jackharrhy requested changes
everything works as expected, except for the `messybanner.lua` file not running on my system, maybe give a readme with running instructions?

2020-01-27 17:06 UTC, jackharrhy commented on week-02/theteamaker/messybanner.lua
> +lines = {}
![image](https://user-images.githubusercontent.com/6486417/73196104-90ea3280-4109-11ea-8e2c-d8a4c4b3dc83.png)

2020-01-27 17:06 UTC, jackharrhy commented on week-02/theteamaker/messybanner.lua
> +lines = {}
^ can't run file

2020-01-27 17:53 UTC, theteamaker commented on week-02/theteamaker/messybanner.lua
> +lines = {}
fixed, I believe

2020-01-27 17:57 UTC, jackharrhy approved these changes

2020-01-27 17:59 UTC, merged