Add Sudoku win-a-tshirt problem
MUNComputerScienceSociety/ChallengeSet-W2020 pull request #38
Opened 2020-02-16 13:59 UTC by zapme

Added description and sample files to win a t-shirt.

2020-02-16 15:15 UTC, jackharrhy requested changes
thanks for the problem / giving the t-shirt codes away!

two small changes, both regarding dates

this PR shall be merged tomorrow as per previous problem set releases :)

2020-02-16 15:15 UTC, jackharrhy commented on week-06/README.md
> +Submissions can be submitted past **Friday @ 5:00pm (February 14th, 2020)**.
```suggestion
Submissions can be submitted past **Friday @ 5:00pm (February 21st, 2020)**.
```

2020-02-16 15:15 UTC, jackharrhy commented on week-06/README.md
> +# Week 5 (Feb 10th)
```suggestion
# Week 5 (Feb 17th)
```

2020-02-16 15:18 UTC, nint8835 commented on week-06/README.md
> +# Week 5 (Feb 10th)
@jackharrhy Do you mean:
```suggestion
# Week 6 (Feb 17th)
```

2020-02-16 15:19 UTC, jackharrhy commented on week-06/README.md
> +# Week 5 (Feb 10th)
_you right_

2020-02-17 23:44 UTC, jackharrhy approved these changes

2020-02-17 23:44 UTC, merged

2020-02-17 23:44 UTC, jackharrhy commented
merged with errors, will be fixed in future PR